// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZombieSurvivalSocialNetwork.Infrastructure.Contexts;

namespace ZombieSurvivalSocialNetwork.Migrations
{
    [DbContext(typeof(ZombieDbContext))]
    partial class ZombieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("ZombieSurvivalSocialNetwork.Core.Domain.Entities.InfectionReport", b =>
                {
                    b.Property<int>("ReportedSurvivor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReportingSurvivor")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReportedSurvivor", "ReportingSurvivor");

                    b.ToTable("InfectionReports");
                });

            modelBuilder.Entity("ZombieSurvivalSocialNetwork.Core.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Point")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Water",
                            Point = 4
                        },
                        new
                        {
                            Id = 2,
                            Name = "Food",
                            Point = 3
                        },
                        new
                        {
                            Id = 3,
                            Name = "Medication",
                            Point = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ammunition",
                            Point = 1
                        });
                });

            modelBuilder.Entity("ZombieSurvivalSocialNetwork.Core.Domain.Entities.Survivor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateInfected")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInfected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsInfected");

                    b.ToTable("Survivors");
                });

            modelBuilder.Entity("ZombieSurvivalSocialNetwork.Core.Domain.Entities.SurvivorItem", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SurvivorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "SurvivorId");

                    b.HasIndex("SurvivorId");

                    b.ToTable("SurvivorItems");
                });

            modelBuilder.Entity("ZombieSurvivalSocialNetwork.Core.Domain.Entities.SurvivorsRequestAndResponseResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsResponse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Point")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SurvivorsTradeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("SurvivorsTradeId");

                    b.ToTable("SurvivorsRequestAndResponseResource");
                });

            modelBuilder.Entity("ZombieSurvivalSocialNetwork.Core.Domain.Entities.SurvivorsTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfTrade")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestedSurvivior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestingSurvivior")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SurvivorsTrades");
                });

            modelBuilder.Entity("ZombieSurvivalSocialNetwork.Core.Domain.Entities.SurvivorItem", b =>
                {
                    b.HasOne("ZombieSurvivalSocialNetwork.Core.Domain.Entities.Item", "Item")
                        .WithMany("SurvivorItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZombieSurvivalSocialNetwork.Core.Domain.Entities.Survivor", "Survivor")
                        .WithMany("SurvivorItems")
                        .HasForeignKey("SurvivorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Survivor");
                });

            modelBuilder.Entity("ZombieSurvivalSocialNetwork.Core.Domain.Entities.SurvivorsRequestAndResponseResource", b =>
                {
                    b.HasOne("ZombieSurvivalSocialNetwork.Core.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZombieSurvivalSocialNetwork.Core.Domain.Entities.SurvivorsTrade", "SurvivorsTrade")
                        .WithMany("SurvivorsRequestAndResponseResource")
                        .HasForeignKey("SurvivorsTradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("SurvivorsTrade");
                });

            modelBuilder.Entity("ZombieSurvivalSocialNetwork.Core.Domain.Entities.Item", b =>
                {
                    b.Navigation("SurvivorItems");
                });

            modelBuilder.Entity("ZombieSurvivalSocialNetwork.Core.Domain.Entities.Survivor", b =>
                {
                    b.Navigation("SurvivorItems");
                });

            modelBuilder.Entity("ZombieSurvivalSocialNetwork.Core.Domain.Entities.SurvivorsTrade", b =>
                {
                    b.Navigation("SurvivorsRequestAndResponseResource");
                });
#pragma warning restore 612, 618
        }
    }
}
